### PR TITLE
fix: remove usage of the deprecated helper._

### PR DESCRIPTION
**Pull request by mattlewis92**
I'm not very familiar with lodash so didn't feel comfortable doing the upgrade from 3.x to 4.x as well in case it accidentally introduced bugs.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Comment by kentcdodds** [comment]
Could we get a release of this so the error message goes away please? :-)

**Comment by kentcdodds** [comment]
Ping? Could we get this released?

**Comment by dignifiedquire** [comment]
Done :) sorry for the delay

**Comment by kentcdodds** [comment]
Thank you!

**Pull request merged**
