### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ronapelbaum**
add documentation for json report

### CODE REVIEW

**Comment by ronapelbaum** [comment]
I signed it!

**Comment by brutalcrozt** [comment]
ping , please merge. I want make a PR too to the readme file

**Comment by johnjbarton** [comment]
Please help me understand what you are trying to solve here. karma-coverage/docs/configuration.md lists the json reporter. The current `Advanced, multiple reporter` section is confusing as it is: why would anyone list all of those reporters in their config?

**Comment by johnjbarton** [comment]
closing old PRs, sorry. I will try to keep up to new ones.

**Pull request closed without merging**
