### PR TITLE
added missing instruction to add karma-coverage to plugins

### PR DESCRIPTION
**Pull request by Shawful**
Added code to readme.md to help users avoid the following Karma warning:

Unable to run Coverage with Karma
http://stackoverflow.com/questions/18069865/unable-to-run-coverage-with-karma

### CODE REVIEW

**Comment by Shawful** [comment]
I signed it!

**Comment by Shawful** [comment]
@vojtajina. Noob question here.   I have no idea how to resolve the Travis spacing failures mentioned in this pull request.  Would you please help explain what I need to modify on my end so I may contribute more in the future?  I'm sure it's something simple; I'm just not a frquent contributor.

Thanks in advance!

**Comment by Shawful** [comment]
@vojtajina. Noob question here.   I have no idea how to resolve the Travis spacing failures mentioned in this pull request.  Would you please help explain what I need to modify on my end so I may contribute more in the future?  I'm sure it's something simple; I'm just not a frquent contributor.

Thanks in advance!

**Comment by Dignifiedquire** [comment]
Hey you can ignore the travis failures as they are related to an updated version of eslint. But I'm afraid I have to close this PR. The main reason is that we do not want to advise people to include their plugins as a list in their config, as karma auto loads plugins when it finds them as devDependencies in the package.json: http://karma-runner.github.io/0.13/config/plugins.html 

Could you explain why you needed to add this line to your config?

**Pull request closed without merging**
