### PR TITLE
Adding event callbacks for "writeReport" and "onExit" functions

### PR DESCRIPTION
**Pull request by m-a-r-c-e-l-i-n-o**
Hello, I've been [working on providing a more sustainable coverage solution for a project called "jspm-karma"](https://github.com/Workiva/karma-jspm/pull/147), and if okay with you guys, I would like to use the reporter files for karma-coverage as is. All I really need are callbacks into the `writeReport` and `onExit` functions. Let me know if this is doable, thanks in advance.

### CODE REVIEW

**Comment by m-a-r-c-e-l-i-n-o** [comment]
I signed it!

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@zzo sorry to bring you into this, but I see that you were the latest active contributor. Any chance you could give some feedback on this pr and perhaps merge it (if in the clear)?

**Comment by zzo** [comment]
please update the commit message to follow the guidelines: 
https://karma-runner.github.io/0.13/dev/git-commit-msg.html

**Comment by zzo** [comment]
otherwise looks good to me thanks

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@zzo Thank you for the response! How's that?

**Comment by Blackbaud-PaulCrowder** [comment]
Any chance we can get a release with this feature?  Right now we're having to point directly to the repo instead of NPM since we rely on this feature.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@zzo ^^ Could you perhaps provide a bit more assistance?
@Blackbaud-PaulCrowder Curious, if it's okay to ask, what are you guys using it for?

**Comment by dignifiedquire** [comment]
just published `1.1.0`

**Comment by zzo** [comment]
thanks @dignifiedquire beat me to it :)

**Comment by Blackbaud-PaulCrowder** [comment]
We're using the `_onWriteReport` callback to pass the coverage files to [remap-istanbul](https://github.com/SitePen/remap-istanbul) since our original source code is TypeScript and not JavaScript.

**Pull request merged**
