### PR TITLE
fix(in-memory-reporter): Fix bug in new InMemoryReport, now using null-checks

### PR DESCRIPTION
**Pull request by nicojs**
Solve issue #218

### CODE REVIEW

**Comment by dignifiedquire** [comment]
thanks, can you change the commit message to `fix(in-memory-reporter): ...` please?

**Comment by nicojs** [comment]
Done

**Comment by nicojs** [comment]
@dignifiedquire Are you still waiting on an action from me?

**Comment by dignifiedquire** [comment]
@nicojs one tiny thing then we can merge it, there is `:` missing in your commit message behind the `)`. If you could fix this I can merge and release a new update

**Comment by nicojs** [comment]
Ok, done, sorry about the mess, i guess it was late. Maybe it is a good thing to add a git hook or something for this rule.

**Comment by dignifiedquire** [comment]
@nicojs yeah we have that in the main repo I just haven't set it up for the 500 other repos.. :/

**Pull request merged**
