### PR TITLE
Use _.contains instead of _.includes

### PR DESCRIPTION
**Pull request by cletusw**
Re-enables support for lodash 2

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, could you update the commit message to our [guidelines](http://karma-runner.github.io/0.12/dev/git-commit-msg.html) then it looks good.

**Comment by Dignifiedquire** [comment]
Fixed it myself thanks.

**Comment by Dignifiedquire** [comment]
Merged as 411beb1f8dc5d2880c275ae67aa960e114517d35

**Comment by Dignifiedquire** [comment]
Published as `0.4.2`

**Comment by cletusw** [comment]
@Dignifiedquire Awesome! Thanks.

**Pull request closed without merging**
