### PR TITLE
Update dependencies and include missing peer dependency

### PR DESCRIPTION
**Pull request by BridgeAR**
Right now we can't update istanbul with our shrinkwrap file, since the version is restricted to ^0.3.15. Istanbul had no breaking changes and only added some features as documented in the [changelog](https://github.com/gotwarlost/istanbul/blob/master/CHANGELOG.md).

I also added the peer dependency `eslint-plugin-standard` as npm 3 will otherwise not work with this module.

All tests pass, so I guess this is ready to merge.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, can you remove the version bump please, as that will be done when the release is triggered and change the commit message to follow our [guideline](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) ?

**Comment by BridgeAR** [comment]
Sry, I missed that. I thought while being at it I'll check what other deps might be updated too. So I'll add them too, if you do not mind.

**Comment by Dignifiedquire** [comment]
Sure thing, thanks

**Comment by BridgeAR** [comment]
Ok I checked all dependencies and I could not find any breaking changes besides a notice about a new peer dependency in [one of the packages](https://github.com/btford/grunt-conventional-changelog/blob/master/CHANGELOG.md). Chai does not have a changelog anymore but the tests pass, so I guess that's fine.

The only "bad thing" that I saw is that the peer dependencies require older versions and there's a mismatch warning in that case. But as there's no breaking change in between everything should be good to go. Besides: this should be fixed as soon as they update their dependencies too.

**Comment by Dignifiedquire** [comment]
Thanks, this looks good to me, just squash the commits into one and update the commit message and we are good to go

**Comment by BridgeAR** [comment]
Squashed

I'm uncertain what change you want for the message besides the default message change while squashing

**Comment by Dignifiedquire** [comment]
Something like this: `fix: Update dependencies and devDependencies`

**Comment by BridgeAR** [comment]
Done

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
