### PR TITLE
feat(preprocessor): free instrumenter

### PR DESCRIPTION
**Pull request by douglasduteil**
Allow any Istanbul instrumenter to be used in the karma-coverage.
Will help #120

Closes #101 #49

BREAKING CHANGE: Karma-coverage does not ship with additional instrumenter. You need to explicitly install the instrumenter you need.

Removed **Ibrik** instrumenter that need to be installed explicitly.

Quick list of known community instrumenters :
- [Ibrik](https://github.com/Constellation/ibrik) (CoffeeScript files instrumenter).
- [Ismailia](https://github.com/Spote/ismailia) (ES6 files instrumenter using Traceur).
- [Isparta](https://github.com/douglasduteil/isparta) (ES6 files instrumenter using 6to5).

### CODE REVIEW

**Comment by johlrich** [comment]
:+1: 

Used this concept in a fork with Isparta to get es6 file coverage via 6to5. Having the ability to pass through options also helped.

**Comment by mairatma** [comment]
:+1:
Also using the fork with Isparta, which is really useful when testing modules using es6. Would be great to have this be available on the official karma-coverage plugin.

**Comment by eduardolundgren** [comment]
:+1:

**Comment by maksimr** [comment]
@douglasduteil Thanks!
Seems it's breaking changes, can you version increase version of `karma-coverage`

**Comment by douglasduteil** [comment]
Yes @maksimr  I can do it. Would you like it to be a major (1.0.0) or a minor bump (0.3.0) ?

**Comment by maksimr** [comment]
@douglasduteil minor bump `0.3.0`

Thanks

**Comment by douglasduteil** [comment]
Alright

**Comment by maksimr** [comment]
@douglasduteil Thanks!

**Comment by DecipherCode** [comment]
Please for the love of God update the README.md.................................................................................................................................................................................................................................................................................................................

**Pull request merged**
