### PR TITLE
Add `coverageStream` option to collect coverage data for downstream use

### PR DESCRIPTION
**Pull request by glan**
- ~~added report type 'none' to prevent output of HTML reports~~

### CODE REVIEW

**Comment by glan** [comment]
This change allows a writeable stream `coverageStream` to be passed to karma-coverage which captures coverage data.

### Example:

``` js
var testCoverageStream = es.through();

gulp.src(testFiles, {
      read: false
    })
    .pipe(browserify({
      debug: true,
      transform: [browserifyIstanbul()]
    }))
    .pipe(karma({
      frameworks: ['jasmine'],
      reporters: ['coverage'],
      browsers: ['PhantomJS'],
      coverageReporter: {
        coverageStream: testCoverageStream,
      },
      action: 'run'
    }));

testCoverageStream.pipe(customReporter);
```

**Comment by glan** [comment]
@vojtajina @aymericbeaumet any feed back for this?

**Comment by glan** [comment]
@maksimr @mwinche are you guys free to take a look?

**Comment by maksimr** [comment]
@glan please follow [commit message convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)

What does `customCoverageReporter`?
Maybe you want write custom `karma-reporter` instead.

**Comment by glan** [comment]
Thanks @maksimr I'll get those commit messages updated. The `customCoverageReporter` produces a report from a stream of coverage data.

Let me take a look at if this could could be implemented as a reporter.

**Comment by maksimr** [comment]
>Let me take a look at if this feature could be implemented as a reporter.

For example inherit from karma-coverage, and implement what you want.

```js
var KarmaCoverageReporter = require('karma-coverage/reporter');
var MyCustomReporter = function(){
   var reporter = KarmaCoverageReporter.apply(this,arguments);
   var onRunComplete = reporter.onRunComplete;

   reporter.onRunComplete = function(){
   // you code
   // ....
   return onRunComplete.apply(this,arguments);
   };
};
MyCustomReporter.$inject = KarmaCoverageReporter.$inject;
module.exports = MyCustomReporter;
```

**Comment by glan** [comment]
@maksimr good idea!

**Comment by Dignifiedquire** [comment]
@glan is this PR still relevant or can you go with the custom standalone version?

**Comment by Dignifiedquire** [comment]
Closing due to inactivity

**Pull request closed without merging**
