### PR TITLE
Use latest istanbul lib packages

### PR DESCRIPTION
**Pull request by pr1sm**
### Changes
- Switch to using the `istanbul-lib-*` packages instead of the deprecated `istanbul` package
  - See https://github.com/karma-runner/karma-coverage/issues/375#issuecomment-481749619 for a short description of what each packages does
- Update unit tests

This PR should address #375

### CODE REVIEW

**Comment by dogoku** [comment]
@pr1sm awesome work!
Will give this a go (on a repo with 1000s of tests) and let you know if anything pops up.

**Comment by mschaaf** [comment]
I tested this PR on one of my projects and it works. Thanks.

**Comment by limonte** [comment]
tested this PR on https://github.com/sweetalert2/sweetalert2 project, all is well, please make a release :rocket:

**Comment by limonte** [comment]
ping @zzo @dignifiedquire please make a release

**Comment by Goran216** [comment]
Ping! @zoo @dignifiedquire

**Comment by zzo** [comment]
you want @johnjbarton I think...

**Comment by johnjbarton** [comment]
done

**Comment by Goran216** [comment]
I understand that this is not related to karma-coverage but I am trying to ignore some private methods with `/* istanbul ignore next */` and it doesn't work. I thought it's because karma-coverage not using latest istanbul features but now that it's updated it's still the same. So frustrating. Does anyone have any idea?

**Pull request merged**
