### PR TITLE
docs(config): Add in-memory reporter

### PR DESCRIPTION
**Pull request by nicojs**
Added docs for in-memory-reporter feature #216

### CODE REVIEW

**Comment by nicojs** [comment]
ah wait, typo

**Comment by nicojs** [comment]
And fixed the typo

**Comment by dignifiedquire** [comment]
Thanks, just change the commit message to `docs(config): Add in-memory reporter` please

**Comment by nicojs** [comment]
Done, also changed the title of this PR

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
