### PR TITLE
Upgrade to lib-istanbul-api

### PR DESCRIPTION
**Pull request by MichaReiser**
A very early draft of an upgrade to lib-istanbul-api. The configuration differs from the existing one (uses the format of istanbul-api) and features like check coverage are still missing. But it might be a good start if someone wants to seriously upgrade to lib-istanbul-api. 

I just wanted to share it, if it is not needed, just close the pull request, 

Cheers.

### CODE REVIEW

**Comment by mramato** [comment]
I'm really interested in this, given that the current istanbul used by karma-coverage is dead in favor of the new library (and they have made significant performance improvements).  Are there any plans by the maintainers to finish this up and merge it?

**Comment by dignifiedquire** [comment]
This is needed, but I don't think I will have time to work on it anytime soon.

**Comment by DatenMetzgerX** [comment]
What's the chance of a (cleanly made) pull request to be accepted, even if some features - e.g. like coverage check - are still missing?

**Comment by dignifiedquire** [comment]
I would be okay with merging it into a `beta` branch on here, and publish as a `beta` version to npm. But for it to go into a regular release we need feature parity with what is currently there.

**Comment by megamindbrian** [comment]
Any progress on this?

**Comment by MichaReiser** [comment]
I had no time to work further on this.

**Comment by brutalcrozt** [comment]
what kind of task is not done yet?

**Comment by johnjbarton** [comment]
closing old PRs, sorry. I will try to keep up to new ones.

**Pull request closed without merging**
