### PR TITLE
fix: exit code when reporter file is not provided

### LINKED ISSUE #485: Exit code 0 even if the coverage fails when reporter's file is missing
As described [here](https://stackoverflow.com/questions/74728524/nrwl-nx-running-tests-in-the-ci-does-not-fail-the-build-when-the-coverage-requir/74729807#74729807), when the `file` parameter of a reporter inside the `reporters` array of `karma.config.js` is NOT provided, the exit code will always be `0` even if the coverage requirements are not met.

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Closes https://github.com/karma-runner/karma-coverage/issues/485

### CODE REVIEW

**Review by anthony-redFox — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks for the code review, can this be merged @anthony-redFox ?

**Comment by anthony-redFox** [comment]
Hello, I had permission to merge some times ago, but for now I don't have it. @jginsburgn Could you please merge commit.

**Comment by jginsburgn** [comment]
I am no longer part of the Karma project. The owners can be reached at @karma-runner/google-web-test-team .

**Comment by ruffin--** [comment]
This is a pretty important PR for me -- I need builds, etc, to key off of coverage values, which requires non-zero return values when coverage fails. Hacking this one word change into my `node_modules` does seem to fix things!

Anybody home at @karma-runner/google-web-test-team ? 🙏 😉

**Comment by ruffin--** [comment]
@jginsburgn that didn't seem to light anyone up. https://github.com/karma-runner seems to suggest contacting karma-users@googlegroups.com and there are a number of people listed [here](https://github.com/orgs/karma-runner/people) (including yours!).

Any idea who best to contact directly? Curation of this project seems to have gone stale.

**Pull request merged**
