### PR TITLE
fix: do not dispose collectors before they are written

### PR DESCRIPTION
**Pull request by mwinche**
fixes: https://github.com/karma-runner/karma-coverage/issues/132

### CODE REVIEW

**Comment by mwinche** [comment]
Can we get some eyes on this PR? I don't think it is wise to another release without addressing the issue this addresses.

**Comment by mwinche** [comment]
@maksimr It is probably a good thing that the automation hasn't picked up the release yet. I think if the bug that this fixes goes out, it would be quite bad (breaking anyone using 'html' and 'text-summary' or 'text' reporters together).

Could you review this PR and the issue it fixes?

Regarding the failure, it is failing on Node 0.8 before it even runs any code:

> The command "npm config set loglevel warn" failed and exited with 1 during .

I'm guessing this is an environmental issue. But I'm happy to do what I can to make it pass.

**Comment by maksimr** [comment]
@mwinche Thanks!

**Comment by Dignifiedquire** [comment]
Thanks, and sorry for the big delay, the PR itself looks good to me. Could you please rebase onto the latest master so I can merge it.

**Comment by mwinche** [comment]
@Dignifiedquire I'll get right on it!

**Comment by mwinche** [comment]
@googlebot signed

**Comment by Dignifiedquire** [comment]
The code style changed a bit in latest version, so make sure you run `grunt eslint` to ensure your code passes the requirements please.

**Comment by mwinche** [comment]
@Dignifiedquire No problem, still going through it. I'll let you know when I'm done.

**Comment by Dignifiedquire** [comment]
Thanks, just wanna get the release out with as much as I can get :)

**Comment by mwinche** [comment]
@Dignifiedquire Okay I fixed style issues and squashed, just waiting on Travis now.

Excited that this will get released soon! :smile:

**Pull request merged**
